-- Canonical creator segment types for `profiles.type` (see docs/creator_type_rows.csv).
CREATE TABLE IF NOT EXISTS public.creator_type (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  key text NOT NULL UNIQUE,
  name_th text NOT NULL,
  name_en text NOT NULL
);

INSERT INTO public.creator_type (id, key, name_th, name_en)
VALUES
  (1, 'assetwise_staff', 'พนักงาน', 'AssetWise'),
  (2, 'asw_household', 'ลูกบ้าน', 'ASW Household'),
  (3, 'miss_world_th', 'Miss World Thailand', 'Miss World Thailand'),
  (4, 'mister_int', 'Mister International', 'Mister International'),
  (5, 'miss_th', 'นางสาวไทย', 'Miss Thailand'),
  (6, 'mr_mrs_global', 'Mr. & Mrs. Global Thailand', 'Mr. & Mrs. Global Thailand')
ON CONFLICT (key) DO UPDATE SET
  name_th = EXCLUDED.name_th,
  name_en = EXCLUDED.name_en;

-- Readable by the app anon key (same pattern as `creator_categories`: no RLS on reference tables).
